minimumReleaseAge: 1440

shamefullyHoist: true
shellEmulator: true

allowBuilds:
  '@parcel/watcher': true
  '@tailwindcss/oxide': true
  esbuild: true
  sharp: true
  simple-git-hooks: true
  unrs-resolver: true
  vue-demi: true
  workerd: true
