shamefullyHoist: true
shellEmulator: true
trustPolicy: no-downgrade
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver
  - vue-demi
  - workerd
